-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgzaVh3uZl7DhUwmjh
hrH5KwKvRuf9zelVLeAtTW1CyzCgCgYIKoZIzj0DAQehRANCAAR3ojtsgvS3Hb2a
AeAPS+DjUgWukmUG0b6+9w5W1tWAr4+VkojTJeGKD6kkuzxKdpdaGPVFvbsFL3Il
FFRiiiNl
-----END PRIVATE KEY-----