name: music_lyrics
description: A new Flutter project.

publish_to: 'none'

version: 1.1.0+1  #// 更新

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  sqflite:  #追加
  path: ^1.8.3  #追加

  on_audio_query: ^2.9.0  #追加
  permission_handler: ^10.3.0 #追加
  audioplayers: ^5.2.0  #追加
  flutter_riverpod: ^2.3.6  #追加
  wakelock: ^0.6.2  #追加
  shared_preferences: ^2.1.2 #追加
  http: ^1.1.0  #追加
  persistent_bottom_nav_bar_v2: ^4.2.8 #追加
  flutter_native_splash: ^2.3.1 #追加
  url_launcher: ^6.1.12 #追加
  path_provider: ^2.0.15 #追加
  flutter_launcher_icons: ^0.13.1 #追加
  google_mobile_ads: ^3.1.0 #追加
  tutorial_coach_mark: ^1.2.11  #追加
  flutter_colorpicker: ^1.0.3 #追加

#追加
flutter_icons:       
  android: true
  ios: true
  image_path: "assets/images/app_icon.png"
  adaptive_icon_background: "assets/images/splash_white.png"
  adaptive_icon_foreground: "assets/images/app_icon.png"

#追加
flutter_native_splash:
  image: assets/images/splash_white.png
  color: '#fffbfe'
  image_dark: assets/images/splash_white.png
  color_dark: '#fffbfe'
  android_12:
    image: 'assets/images/splash_white.png'
    color: '#fffbfe'
    image_dark: assets/images/splash_white.png
    color_dark: '#fffbfe'

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  # -----フォントの追加-----
  fonts:
    - family: Noto Sans JP
      fonts:
        - asset: assets/fonts/Noto_Sans_JP/NotoSansJP-Regular.otf
    - family: shippori3
      fonts: 
        - asset: assets/fonts/shippori3/ShipporiMincho-OTF-Regular.otf
  # -----ここまで-----